// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"1stpeson","status":true,"description":"This plugin makes your game a first person labyrinth explorer.","parameters":{"View Distance":"3","Field Of View":"75","Light Color":"#ffffff","Wall Terrain":"1","Ceiling Region":"0","3D Anaglyph":"0","Texture Filter":"linear","Texture Format":"png","Texture Anisotropy":"1","Antialiasing":"0","Optimization Level":"none"}}
];
